version: "3.2"

services:
  sa-api:
    container_name: sa-api
    build: .
    volumes:
      - ./:/sa-api
      - ./app.conf:/etc/nginx/conf.d/app.conf
    ports:
      - "80:80"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.main



